# (-*- shell-script -*-)

# MacVim
alias mvim='/Applications/MacVim.app/Contents/MacOS/Vim -g'
alias mvimdiff='mvim -d0'
alias mview='mvim -R'

# Make sure Python virtualenv is setup nicely
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
#source /Library/Frameworks/Python.framework/Versions/2.6/bin/virtualenvwrapper_bashrc
